#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 14 10:43:10 2018

@author: ankitjha
"""

#Generating some dataset.
#These codes are implemented with the help of CS231n Stanford University Course.
import numpy as np, matplotlib.pyplot as plt 
#number of points per class
N=100
#dimentionality of the data
D=2 # That is 2 dimensional data
#number of classes
K=3
x=np.zeros((N*K,D)) 
y=np.zeros(N*K, dtype='uint8')

for i in range(K):
    ix=range(N*i,N*(i+1))
    #radius
    r=np.linspace(0,0.1,N) 
    t=np.linspace(i*4,(i+1)*4,N)+np.random.randn(N)*0.2
    x[ix]=np.c_[r*np.sin(t),r*np.cos(t)]
    y[ix]=i

plt.scatter(x[:,0],x[:,1],c=y,s=10,cmap=plt.cm.Spectral)
#c= color code , s=size of the data samples
plt.show()
