#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 16 15:49:05 2018

@author: ankitjha
"""
# It is an example of simple neural network with 3 layers
#(one input layer, one hidden layer and one output layer)

import numpy as np, matplotlib.pyplot as plt

np.random.seed(0)
x=np.array(([2,9,5],[1,5,6],[3,6,9]),dtype=float)
y=np.array(([91],[90],[92]),dtype=float)

x=x/np.amax(x,axis=0)
y=y/100

class Neural_Network(object):
    def __init__(self):
        self.inputSize=3
        self.outputSize=1
        self.hiddenSize=7
        
        self.w1=np.random.randn(self.inputSize,self.hiddenSize)
        self.w2=np.random.randn(self.hiddenSize,self.outputSize)
        
        
    def forward(self,x):
        self.z1=np.dot(x,self.w1)
        self.z2=self.sigmoid(self.z1)
        self.z3=np.dot(self.z2,self.w2)
        out=self.sigmoid(self.z3)
        return out
    
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoid_prime(self,s):
        return s*(1-s)
    
    def backward(self,x,y,o):
        self.o_error=y-o
        self.o_delta=self.o_error * self.sigmoid_prime(o)
        
        self.z2_error=self.o_delta.dot(self.w2.T)
        self.z2_delta=self.z2_error * self.sigmoid_prime(self.z2)
        
        self.w1 +=x.T.dot(self.z2_delta)
        self.w2 +=self.z2.T.dot(self.o_delta)
        
    def train(self,x,y):
        o=self.forward(x)
        self.backward(x,y,o)
        
    def visualize(self,i,l):
        plt.plot(i,l)# plot between loss and iteration
    
NN=Neural_Network()
o=NN.forward(x)
temp=[]
weight_visualize=[]
loss_visualize=[]
for i in range(100):
    t=i
    temp=np.append(temp,t)
    loss_visualize=np.append(loss_visualize,np.mean(np.square(y-NN.forward(x))))
    print("input:\n"+str(x))
    print("actual output:\n"+str(y))
    print("predicted output:\n"+str(NN.forward(x)))
    print("loss:\n"+str(np.mean(np.square(y-NN.forward(x)))))
    print("\n")
    wv=NN.w1
    weight_visualize=np.append(weight_visualize,np.mean(wv))
    

    NN.train(x,y)

fig=plt.figure()
plt.subplot(1,2,1),plt.title('iteration vs loss'),plt.xlabel('Iteration'),plt.ylabel('Loss'),NN.visualize(temp,loss_visualize)
plt.subplot(1,2,2),plt.title('weights vs loss'),plt.xlabel('Weight'),plt.ylabel('Loss'),NN.visualize(weight_visualize,loss_visualize)
fig.savefig('Iteration_weights_Loss.png')
